from app import db

class clasedbasistencia(db.Model):
    entryid = db.Column(db.Integer, primary_key=True)
    attendanceid = db.Column(db.String(255), index=True, unique=False, nullable=False)
    courseid = db.Column(db.String(255), index=True, unique=False, nullable=False)
    coursename = db.Column(db.String(255), index=True, unique=False, nullable=False)
    dayoftheweek = db.Column(db.String(255), index=True, unique=False, nullable=False)
    teacherfirstname = db.Column(db.String(255), index=True, unique=False, nullable=False)
    teacherlastname = db.Column(db.String(255), index=True, unique=False, nullable=False)
    teacherid = db.Column(db.String(255), index=True, unique=False, nullable=False)
    studentfirstname = db.Column(db.String(255), index=True, unique=False, nullable=False)
    studentlastname = db.Column(db.String(255), index=True, unique=False, nullable=False)
    studentid = db.Column(db.String(255), index=True, unique=False, nullable=False)
    weekatt1 = db.Column(db.Boolean)
    weekatt2 = db.Column(db.Boolean)
    weekatt3 = db.Column(db.Boolean)
    weekatt4 = db.Column(db.Boolean)
    weekatt5 = db.Column(db.Boolean)
    weekatt6 = db.Column(db.Boolean)
    weekatt7 = db.Column(db.Boolean)
    weekatt8 = db.Column(db.Boolean)
    weekatt9 = db.Column(db.Boolean)
    weekatt10 = db.Column(db.Boolean)
    weekatt11 = db.Column(db.Boolean)
    weekatt12 = db.Column(db.Boolean)
    weekatt13 = db.Column(db.Boolean)
    weekatt14 = db.Column(db.Boolean)
    weekatt15 = db.Column(db.Boolean)
    def __repr__(self):
        return '<IDofrow {}>'.format(self.entryid)
